site_name: Probabilistic Forecasting of Nocturnal Hypoglycemia
theme:
  name: material
  features:
    - navigation.tabs
    - navigation.sections
    - search.highlight

nav:
  - Home: index.md
  - User Guide:
      - Usage: user-guide/usage.md
      - Getting Started: user-guide/getting-started.md
      - Installation: user-guide/installation.md
      - Data:
        - Data Preparation: user-guide/datasets/data-preparation.md
      - Modeling:
        - Model Training: user-guide/modeling/model-training.md
        - Model Evaluation: user-guide/modeling/model-evaluation.md
      - Benchmarking:
        - Model Benchmarking: user-guide/benchmarking/model-benchmarking.md
        - WATGPU Benchmarking: user-guide/benchmarking/watgpu-benchmark.md
  - API Reference: api-reference.md
  - Contributing: contributing.md

markdown_extensions:
  - pymdownx.highlight
  - pymdownx.superfences
  - pymdownx.arithmatex:
      generic: true
