site_name: Probabilistic Forecasting of Nocturnal Hypoglycemia
theme:
  name: material
  features:
    - navigation.tabs
    - navigation.sections
    - search.highlight

nav:
  - Home: index.md
  - User Guide:
      - Installation: user-guide/installation.md
      - Usage: user-guide/usage.md
      - WATGPU Benchmarking: user-guide/watgpu-benchmark.md
  - API Reference: api-reference.md
  - Contributing: contributing.md

markdown_extensions:
  - pymdownx.highlight
  - pymdownx.superfences
  - pymdownx.arithmatex:
      generic: true
