#!/usr/bin/env python3
# Copyright (c) 2025 Blood-Glucose-Control
# Licensed under Custom Research License (see LICENSE file)
"""Three-model probabilistic forecast row — NeurIPS publication figure.

Single row of three panels (Chronos-2 | Moirai | TFT) showing the same
representative Aleppo hypoglycaemic episode for all models.  Context window
covers 4 h back from midnight; forecast spans 8 h ahead.  Secondary axes show
normalised IOB and COB over the context window.

Episode pre-selection
---------------------
Run ``--find-candidates`` once to search all three NPZ files and print
ready-to-paste entries for the ``CANDIDATES`` table below.  Once populated,
the script renders immediately without any search.

Usage
-----
Find and print the best hypo episodes::

    python scripts/visualization/plot_three_model_row.py --find-candidates
    python scripts/visualization/plot_three_model_row.py --find-candidates --top-n 10

Render the figure (uses CANDIDATES[ACTIVE_CANDIDATE])::

    python scripts/visualization/plot_three_model_row.py
    python scripts/visualization/plot_three_model_row.py --output fig3_forecast_row

Outputs:
    results/figures/three_model_row.pdf  (vector — for submission)
    results/figures/three_model_row.png  (raster  — for preview)
"""

from __future__ import annotations
import argparse
import sys
import textwrap

import matplotlib

matplotlib.use("Agg")
import matplotlib.lines as mlines
import matplotlib.patches as mpatches
import matplotlib.pyplot as plt
import numpy as np
import pandas as pd


# ══════════════════════════════════════════════════════════════════════════════
# CONFIG — edit freely; do not modify code below the END-CONFIG marker.
# ══════════════════════════════════════════════════════════════════════════════

from pathlib import Path

PROJECT_ROOT = Path(__file__).resolve().parents[2]

# ── Experiment run directories (relative to PROJECT_ROOT) ─────────────────────
RUN_DIRS: dict[str, str] = {
    "Chronos-2": "experiments/nocturnal_forecasting/512ctx_96fh/chronos2/2026-04-25_183908_aleppo_2017_finetuned",
    "Moirai": "experiments/nocturnal_forecasting/512ctx_96fh/moirai/2026-04-19_2045_aleppo_2017_finetuned_rerun01",
    "TFT": "experiments/nocturnal_forecasting/512ctx_96fh/tft/2026-04-29_194226_aleppo_2017_finetuned",
}

DATASET = "aleppo_2017"
DATA_DIR = PROJECT_ROOT / "cache" / "data" / "aleppo_2017" / "processed"

# ── Pre-searched episode candidates ───────────────────────────────────────────
# Run with --find-candidates to populate this table.  After running, copy the
# printed dicts here.  Set ACTIVE_CANDIDATE to select which episode to render.
#
# Keys
# ----
#   episode_idx  row index into forecasts.npz (0-based)
#   episode_id   human-readable, e.g. "ale_10::ep005"
#   patient_id   maps to cache/data/aleppo_2017/processed/<id>_full.csv
#   anchor       midnight date string, e.g. "2017-06-15"
#   min_bg       minimum actual BG in forecast window (mmol/L)
#   rmse_c2 / rmse_mo / rmse_tft   per-episode median-forecast RMSE
#   pct_c2  / pct_mo  / pct_tft    RMSE percentile rank (0=best, 100=worst)
CANDIDATES: list[dict] = [
    # Generated by: python scripts/visualization/plot_three_model_row.py --find-candidates --top-n 6
    # All 6 are within the top-10 % RMSE for every model simultaneously.
    # Sorted by score = BG-range + 2×hypo-depth (descending).
    {
        "episode_idx": 2057,
        "episode_id": "ale_139::ep077",
        "patient_id": "ale_139",
        "anchor": "2020-06-05",
        "min_bg": 2.61,
        "rmse_c2": 0.699,
        "rmse_mo": 0.940,
        "rmse_tft": 0.566,
        "pct_c2": 5.7,
        "pct_mo": 9.3,
        "pct_tft": 2.9,
    },
    {
        "episode_idx": 3130,
        "episode_id": "ale_23::ep119",
        "patient_id": "ale_23",
        "anchor": "2020-07-05",
        "min_bg": 3.0,
        "rmse_c2": 0.843,
        "rmse_mo": 0.674,
        "rmse_tft": 0.812,
        "pct_c2": 9.6,
        "pct_mo": 2.8,
        "pct_tft": 8.6,
    },
    {
        "episode_idx": 316,
        "episode_id": "ale_211::ep009",
        "patient_id": "ale_211",
        "anchor": "2020-09-03",
        "min_bg": 2.83,
        "rmse_c2": 0.639,
        "rmse_mo": 0.943,
        "rmse_tft": 0.717,
        "pct_c2": 4.1,
        "pct_mo": 9.5,
        "pct_tft": 6.4,
    },
    {
        "episode_idx": 3106,
        "episode_id": "ale_23::ep095",
        "patient_id": "ale_23",
        "anchor": "2020-05-31",
        "min_bg": 3.27,
        "rmse_c2": 0.814,
        "rmse_mo": 0.719,
        "rmse_tft": 0.853,
        "pct_c2": 8.8,
        "pct_mo": 3.7,
        "pct_tft": 9.9,
    },
    {
        "episode_idx": 2034,
        "episode_id": "ale_139::ep054",
        "patient_id": "ale_139",
        "anchor": "2020-04-11",
        "min_bg": 3.5,
        "rmse_c2": 0.281,
        "rmse_mo": 0.748,
        "rmse_tft": 0.654,
        "pct_c2": 0.1,
        "pct_mo": 4.1,
        "pct_tft": 4.8,
    },
    {
        "episode_idx": 3104,
        "episode_id": "ale_23::ep093",
        "patient_id": "ale_23",
        "anchor": "2020-05-29",
        "min_bg": 3.61,
        "rmse_c2": 0.591,
        "rmse_mo": 0.782,
        "rmse_tft": 0.553,
        "pct_c2": 3.1,
        "pct_mo": 4.8,
        "pct_tft": 2.7,
    },
]

# Which entry in CANDIDATES to render (0 = top-ranked).
ACTIVE_CANDIDATE = 2

# ── Output ────────────────────────────────────────────────────────────────────
OUTPUT_DIR = PROJECT_ROOT / "results" / "figures"
OUTPUT_STEM = "three_model_row"
OUTPUT_FORMATS: list[str] = ["pdf", "png"]
OUTPUT_DPI = 300  # raster PNG resolution

# ── Page geometry (NeurIPS single-column = 5.5 in textwidth) ─────────────────
FIGURE_WIDTH_IN = 5.5
FIGURE_HEIGHT_IN = 2.6

# ── Subplot spacing ───────────────────────────────────────────────────────────
SUBPLOT_LEFT = 0.08  # room for primary y-axis label
SUBPLOT_RIGHT = 0.86  # room for secondary (IOB/COB) y-axis on rightmost panel
SUBPLOT_TOP = 0.86  # room for panel titles
SUBPLOT_BOTTOM = 0.17  # room for shared legend
SUBPLOT_WSPACE = 0.08  # gap between panels (subplot-width fraction)

# ── Time window ───────────────────────────────────────────────────────────────
CONTEXT_HOURS = 8  # hours of context visible in each panel (48 steps)
FORECAST_HOURS = 8  # hours of forecast horizon              (96 steps)
INTERVAL_MINS = 5  # CGM cadence in minutes

# ── BG y-axis limits ─────────────────────────────────────────────────────────
YLIM_BG_MIN = 0
YLIM_BG_MAX = 12.0

# ── Clinical thresholds ───────────────────────────────────────────────────────
HYPO_THRESHOLD = 3.9  # mmol/L — red dashed line
HYPER_THRESHOLD = 10.0  # mmol/L — orange dashed line

# ── Model forecast colours ────────────────────────────────────────────────────
MODEL_STYLES: dict[str, dict] = {
    "Chronos-2": {
        "median_color": "#c5449a",
        "fill_50_color": "#f2c6e8",
        "fill_80_color": "#f9e5f5",
    },
    "Moirai": {
        "median_color": "#1565c0",
        "fill_50_color": "#90caf9",
        "fill_80_color": "#e3f2fd",
    },
    "TFT": {
        "median_color": "#2e7d32",
        "fill_50_color": "#a5d6a7",
        "fill_80_color": "#e8f5e9",
    },
}

# ── IOB / COB secondary axis ──────────────────────────────────────────────────
# IOB and COB are each normalised to [0, 1] relative to their own peak value
# so they can share a single secondary axis regardless of unit differences.
IOB_COLOR = "#546e7a"  # blue-gray
COB_COLOR = "#8d6e63"  # warm brown
IOB_ALPHA = 0.85
COB_ALPHA = 0.40
IOB_LW = 0.9
COB_LW = 0.8
SECONDARY_YLIM_TOP = 1.5  # normalised axis upper limit

# ── Context window styling ────────────────────────────────────────────────────
CONTEXT_SHADE_COLOR = "#f2f2f2"
CONTEXT_SHADE_ALPHA = 1.0
MIDNIGHT_LINE_COLOR = "#aaaaaa"
MIDNIGHT_LINE_LW = 0.7
MIDNIGHT_LINE_LS = ":"

# ── PI band opacity ───────────────────────────────────────────────────────────
ALPHA_80PI = 0.80
ALPHA_50PI = 0.80

# ── Typography ────────────────────────────────────────────────────────────────
# Set USE_LATEX = True only if a full LaTeX distribution is installed.
USE_LATEX = False
FONT_FAMILY = "serif"
FONT_SIZE_BASE = 7
FONT_SIZE_PANEL_TITLE = 7
FONT_SIZE_AXIS_LABEL = 6.5
FONT_SIZE_TICK = 5.5
FONT_SIZE_LEGEND = 5.5
FONT_SIZE_ANNOTATION = 5.0  # "Hyper" / "Hypo" threshold labels

# ── Line widths ───────────────────────────────────────────────────────────────
ACTUAL_CTX_LW = 1.1  # actual BG in context (solid black)
ACTUAL_FC_LW = 1.1  # actual BG ground-truth in forecast (dashed black)
MEDIAN_LW = 0.9  # median forecast
THRESHOLD_LW = 0.8  # clinical threshold horizontal lines

# ── Legend ────────────────────────────────────────────────────────────────────
LEGEND_NCOL = 6
LEGEND_LOC = "lower center"
LEGEND_BBOX = (0.5, -0.02)
LEGEND_FRAME = False

# ── Episode search (--find-candidates) ───────────────────────────────────────
SEARCH_TOP_N = 5  # default number of candidates to print
SEARCH_MAX_PERCENTILE = 30  # auto-relax 10 → 15 → 20 → 25 → 30

# ══════════════════════════════════════════════════════════════════════════════
# END CONFIG
# ══════════════════════════════════════════════════════════════════════════════


# ── Publication rcParams ──────────────────────────────────────────────────────


def _apply_rcparams() -> None:
    """Push all CONFIG-driven values into matplotlib's global rcParams."""
    if USE_LATEX:
        matplotlib.rcParams.update(
            {"text.usetex": True, "text.latex.preamble": r"\usepackage{amsmath}"}
        )
    matplotlib.rcParams.update(
        {
            "font.family": FONT_FAMILY,
            "font.size": FONT_SIZE_BASE,
            "axes.titlesize": FONT_SIZE_PANEL_TITLE,
            "axes.labelsize": FONT_SIZE_AXIS_LABEL,
            "xtick.labelsize": FONT_SIZE_TICK,
            "ytick.labelsize": FONT_SIZE_TICK,
            "legend.fontsize": FONT_SIZE_LEGEND,
            "lines.linewidth": 1.0,
            "axes.linewidth": 0.5,
            "xtick.major.width": 0.5,
            "ytick.major.width": 0.5,
            "xtick.major.size": 2.5,
            "ytick.major.size": 2.5,
            "xtick.direction": "in",
            "ytick.direction": "in",
            "axes.spines.top": False,
            "axes.spines.right": False,
            "figure.dpi": 150,
        }
    )


# ── Data helpers ──────────────────────────────────────────────────────────────


def interpolate_quantile(
    q_forecasts: np.ndarray,
    q_levels: np.ndarray,
    q_target: float,
) -> np.ndarray:
    """Linearly interpolate a quantile not present in q_levels.

    Parameters
    ----------
    q_forecasts : (n_quantiles, fh)
    q_levels    : (n_quantiles,) sorted ascending
    q_target    : scalar within [q_levels[0], q_levels[-1]]
    """
    if q_target in q_levels:
        return q_forecasts[int(np.searchsorted(q_levels, q_target))]
    idx_hi = int(np.searchsorted(q_levels, q_target))
    idx_lo = idx_hi - 1
    frac = (q_target - q_levels[idx_lo]) / (q_levels[idx_hi] - q_levels[idx_lo])
    return q_forecasts[idx_lo] + frac * (q_forecasts[idx_hi] - q_forecasts[idx_lo])


def _load_npz(model_name: str) -> dict:
    """Load forecasts.npz for the given model name."""
    path = PROJECT_ROOT / RUN_DIRS[model_name] / "forecasts.npz"
    data = np.load(path, allow_pickle=False)
    return {
        "actuals": data["actuals"],  # (n_eps, 96)
        "q_forecasts": data["quantile_forecasts"],  # (n_eps, 9, 96)
        "q_levels": data["quantile_levels"].astype(float),  # (9,)
        "episode_ids": np.array(data["episode_ids"], dtype=str),  # (n_eps,)
    }


def _per_episode_rmse(npz: dict) -> np.ndarray:
    """RMSE of the median (q=0.5) forecast per episode, shape (n_eps,)."""
    q_levels = npz["q_levels"]
    median_idx = int(np.searchsorted(q_levels, 0.5))
    median_fc = npz["q_forecasts"][:, median_idx, :]
    return np.sqrt(np.mean((npz["actuals"] - median_fc) ** 2, axis=1))


# ── Candidate search ──────────────────────────────────────────────────────────


def find_candidates(top_n: int = SEARCH_TOP_N) -> list[dict]:
    """Search all three models for the best shared hypo episodes.

    Criteria
    --------
    * Actual BG dips below HYPO_THRESHOLD at least once in the forecast window.
    * Per-episode median RMSE is within the top P % for *all three* models.
      Auto-relaxes from P=10 in steps of 5 up to SEARCH_MAX_PERCENTILE until
      at least ``top_n`` candidates are found.

    Scoring rewards large BG range (dynamic movement) and deep hypoglycaemia.
    """
    print("Loading NPZ arrays for all three models…")
    model_names = list(RUN_DIRS.keys())
    npzs = {m: _load_npz(m) for m in model_names}

    # Verify that all models evaluated episodes in the same order
    ids_ref = npzs[model_names[0]]["episode_ids"]
    for m in model_names[1:]:
        if not np.array_equal(ids_ref, npzs[m]["episode_ids"]):
            raise ValueError(
                f"episode_ids mismatch between {model_names[0]} and {m}.\n"
                "The three NPZ files must come from evaluation runs that used "
                "identical episode orderings."
            )
    n_eps = len(ids_ref)
    print(f"  Verified: {n_eps:,} episodes aligned across all models.")

    rmses = {m: _per_episode_rmse(npzs[m]) for m in model_names}
    actuals = npzs[model_names[0]]["actuals"]  # identical across models
    has_hypo = actuals.min(axis=1) < HYPO_THRESHOLD

    # Auto-relax percentile threshold
    percentile_steps = list(range(10, SEARCH_MAX_PERCENTILE + 1, 5))
    mask = np.zeros(n_eps, dtype=bool)
    achieved_pct = SEARCH_MAX_PERCENTILE
    for pct in percentile_steps:
        in_pct = np.ones(n_eps, dtype=bool)
        for m in model_names:
            thr = float(np.percentile(rmses[m], pct))
            in_pct &= rmses[m] <= thr
        candidate_mask = has_hypo & in_pct
        if candidate_mask.sum() >= top_n:
            mask = candidate_mask
            achieved_pct = pct
            break
    else:
        # Absolute fallback: all hypo episodes, no RMSE filter
        mask = has_hypo
        achieved_pct = 100

    n_cands = int(mask.sum())
    print(
        f"  {n_cands} shared hypo episodes within P{achieved_pct} RMSE "
        f"for all models (need {top_n})."
    )
    if n_cands == 0:
        print(
            "  WARNING: no qualifying hypo episodes found.\n"
            f"  Check HYPO_THRESHOLD ({HYPO_THRESHOLD}) and "
            f"SEARCH_MAX_PERCENTILE ({SEARCH_MAX_PERCENTILE})."
        )
        return []

    # Score: BG range + extra weight on depth of hypoglycaemia
    min_bgs = actuals.min(axis=1)
    max_bgs = actuals.max(axis=1)
    score = (max_bgs - min_bgs) + 2.0 * np.maximum(0.0, HYPO_THRESHOLD - min_bgs)
    score[~mask] = -np.inf

    top_indices = np.argsort(score)[::-1][:top_n]

    # episodes.parquet rows are aligned 1-to-1 with NPZ episode_ids (same loop order)
    # so we can look up anchor by integer position (iloc[idx]).
    parquet_path = PROJECT_ROOT / RUN_DIRS[model_names[0]] / "episodes.parquet"
    ep_df = pd.read_parquet(parquet_path)
    anchors_arr = pd.to_datetime(ep_df["anchor"]).to_numpy()

    candidates: list[dict] = []
    for idx in top_indices:
        ep_id = str(ids_ref[idx])
        anchor_ts = pd.Timestamp(anchors_arr[idx])
        anchor_str = str(anchor_ts.date())
        pid = ep_id.split("::")[0]
        pct_ranks = {
            m: float(round(100.0 * float((rmses[m] < rmses[m][idx]).mean()), 1))
            for m in model_names
        }
        candidates.append(
            {
                "episode_idx": int(idx),
                "episode_id": ep_id,
                "patient_id": pid,
                "anchor": anchor_str,
                "min_bg": float(round(float(min_bgs[idx]), 2)),
                "rmse_c2": float(round(float(rmses[model_names[0]][idx]), 3)),
                "rmse_mo": float(round(float(rmses[model_names[1]][idx]), 3)),
                "rmse_tft": float(round(float(rmses[model_names[2]][idx]), 3)),
                "pct_c2": pct_ranks[model_names[0]],
                "pct_mo": pct_ranks[model_names[1]],
                "pct_tft": pct_ranks[model_names[2]],
            }
        )
    return candidates


def _print_candidates(candidates: list[dict]) -> None:
    """Print candidate dicts ready to paste into CANDIDATES."""
    print("\n" + "=" * 72)
    print("Top candidates — paste into CANDIDATES in the CONFIG section:")
    print("=" * 72)
    for c in candidates:
        print(
            textwrap.dedent(
                f"""\
                {{
                    "episode_idx": {c['episode_idx']},
                    "episode_id":  "{c['episode_id']}",
                    "patient_id":  "{c['patient_id']}",
                    "anchor":      "{c['anchor']}",
                    "min_bg":      {c['min_bg']},
                    "rmse_c2":  {c['rmse_c2']},  "rmse_mo":  {c['rmse_mo']},  "rmse_tft": {c['rmse_tft']},
                    "pct_c2":   {c['pct_c2']},   "pct_mo":   {c['pct_mo']},   "pct_tft":  {c['pct_tft']},
                }},"""
            )
        )
    print("=" * 72)
    if candidates:
        print(f"\nSet ACTIVE_CANDIDATE = 0  (or 1–{len(candidates) - 1}) to select.\n")


# ── Context data loading ──────────────────────────────────────────────────────


def load_context_data(patient_id: str, anchor: pd.Timestamp) -> dict:
    """Return 4-hour context-window BG, IOB, COB from the patient CSV.

    The data is reindexed to a strict 5-min uniform grid so arrays have a
    guaranteed length of ``CONTEXT_HOURS * 60 // INTERVAL_MINS``.
    Missing values are left as NaN.
    """
    csv_path = DATA_DIR / f"{patient_id}_full.csv"
    df = pd.read_csv(csv_path, parse_dates=["datetime"], index_col="datetime")

    ctx_end = anchor - pd.Timedelta(minutes=INTERVAL_MINS)
    ctx_start = anchor - pd.Timedelta(hours=CONTEXT_HOURS)

    expected_idx = pd.date_range(
        start=ctx_start, end=ctx_end, freq=f"{INTERVAL_MINS}min"
    )
    ctx = df.reindex(expected_idx)

    # Linearly interpolate small gaps (up to 12 steps = 1 h) so the context
    # line renders continuously rather than breaking on missing CGM readings.
    for col in ("bg_mM", "iob", "cob"):
        ctx[col] = pd.to_numeric(ctx[col], errors="coerce").interpolate(
            method="linear", limit=12, limit_direction="both"
        )

    return {
        "bg": ctx["bg_mM"].to_numpy(dtype=float),
        "iob": ctx["iob"].to_numpy(dtype=float),
        "cob": ctx["cob"].to_numpy(dtype=float),
    }


# ── Time axes ─────────────────────────────────────────────────────────────────


def _make_time_axes() -> tuple[np.ndarray, np.ndarray]:
    """Return (ctx_t, fc_t) in decimal hours relative to midnight (t = 0)."""
    n_ctx = CONTEXT_HOURS * 60 // INTERVAL_MINS  # 48
    n_fc = FORECAST_HOURS * 60 // INTERVAL_MINS  # 96
    ctx_t = np.arange(-n_ctx, 0) * INTERVAL_MINS / 60.0
    fc_t = np.arange(n_fc) * INTERVAL_MINS / 60.0
    return ctx_t, fc_t


# ── Panel drawing ─────────────────────────────────────────────────────────────


def _norm_signal(arr: np.ndarray) -> np.ndarray:
    """Normalise arr to [0, 1] by its own finite peak; return zeros if flat."""
    finite = arr[np.isfinite(arr)]
    peak = float(finite.max()) if len(finite) > 0 else 0.0
    if peak < 1e-6:
        return np.zeros_like(arr)
    return arr / peak


def plot_panel(
    ax: plt.Axes,
    model_name: str,
    episode_idx: int,
    npz: dict,
    ctx_data: dict,
    ctx_t: np.ndarray,
    fc_t: np.ndarray,
    is_leftmost: bool,
    is_rightmost: bool,
) -> plt.Axes:
    """Draw one forecast panel onto *ax*.  Returns the secondary (twin) Axes."""
    style = MODEL_STYLES[model_name]
    actuals = npz["actuals"][episode_idx]  # (96,)
    q_fc = npz["q_forecasts"][episode_idx]  # (9, 96)
    q_levels = npz["q_levels"]

    # Quantile traces
    q01 = q_fc[0]
    q09 = q_fc[8]
    q05 = q_fc[int(np.searchsorted(q_levels, 0.5))]  # median
    q025 = interpolate_quantile(q_fc, q_levels, 0.25)
    q075 = interpolate_quantile(q_fc, q_levels, 0.75)

    # ── Context background ─────────────────────────────────────────────────
    ax.axvspan(
        ctx_t[0],
        0.0,
        color=CONTEXT_SHADE_COLOR,
        alpha=CONTEXT_SHADE_ALPHA,
        zorder=0,
        label="_nolegend_",
    )

    # ── Midnight separator ─────────────────────────────────────────────────
    ax.axvline(
        0.0,
        color=MIDNIGHT_LINE_COLOR,
        lw=MIDNIGHT_LINE_LW,
        ls=MIDNIGHT_LINE_LS,
        zorder=1,
        label="_nolegend_",
    )

    # ── Clinical thresholds ────────────────────────────────────────────────
    ax.axhline(
        HYPER_THRESHOLD,
        color="#ff7f0e",
        lw=THRESHOLD_LW,
        ls="-",
        alpha=0.9,
        zorder=2,
        label="_nolegend_",
    )
    ax.axhline(
        HYPO_THRESHOLD,
        color="#d62728",
        lw=THRESHOLD_LW,
        ls="-",
        alpha=0.9,
        zorder=2,
        label="_nolegend_",
    )

    # ── 80 % prediction interval ───────────────────────────────────────────
    ax.fill_between(
        fc_t,
        q01,
        q09,
        color=style["fill_80_color"],
        alpha=ALPHA_80PI,
        zorder=3,
        label="80% PI",
    )
    # ── 50 % prediction interval ───────────────────────────────────────────
    ax.fill_between(
        fc_t,
        q025,
        q075,
        color=style["fill_50_color"],
        alpha=ALPHA_50PI,
        zorder=4,
        label="50% PI",
    )
    # ── Median forecast (dashed) ───────────────────────────────────────────
    ax.plot(
        fc_t,
        q05,
        color=style["median_color"],
        lw=MEDIAN_LW,
        ls=(0, (4, 2)),
        zorder=5,
        label="Median",
    )

    # ── Actual BG — context (solid) ────────────────────────────────────────
    ax.plot(
        ctx_t,
        ctx_data["bg"],
        color="black",
        lw=ACTUAL_CTX_LW,
        zorder=6,
        label="BG",
    )
    # ── Actual BG — forecast ground-truth (solid) ─────────────────────────
    ax.plot(
        fc_t,
        actuals,
        color="black",
        lw=ACTUAL_FC_LW,
        zorder=6,
        label="_nolegend_",
    )

    # ── Context / Forecast span labels (middle panel only) ────────────────
    if not is_leftmost and not is_rightmost:
        ax.text(
            -4.0,
            YLIM_BG_MAX * 0.97,
            "\u2190 Context",
            color="#888888",
            fontsize=FONT_SIZE_ANNOTATION,
            ha="center",
            va="top",
            zorder=7,
        )
        ax.text(
            4.0,
            YLIM_BG_MAX * 0.97,
            "Forecast",
            color="#888888",
            fontsize=FONT_SIZE_ANNOTATION,
            ha="center",
            va="top",
            zorder=7,
        )

    # ── "Hyper" / "Hypo" annotations (leftmost panel only) ────────────────
    if is_leftmost:
        ax.text(
            ctx_t[0] + 0.12,
            HYPER_THRESHOLD + 0.35,
            "Hyper",
            color="#ff7f0e",
            fontsize=FONT_SIZE_ANNOTATION,
            ha="left",
            va="bottom",
            zorder=7,
        )
        ax.text(
            ctx_t[0] + 0.12,
            HYPO_THRESHOLD - 0.35,
            "Hypo",
            color="#d62728",
            fontsize=FONT_SIZE_ANNOTATION,
            ha="left",
            va="top",
            zorder=7,
        )

    # ── Secondary axis: normalised IOB + COB (context window only) ────────
    iob_n = _norm_signal(ctx_data["iob"])
    cob_n = _norm_signal(ctx_data["cob"])

    # Restore right spine for this panel (globally disabled by rcParams)
    ax.spines["right"].set_visible(True)
    ax.spines["right"].set_linewidth(0.5)
    ax.spines["right"].set_color("#888888")

    ax2 = ax.twinx()
    ax2.spines["top"].set_visible(False)
    ax2.spines["left"].set_visible(False)
    ax2.spines["bottom"].set_visible(False)
    ax2.spines["right"].set_visible(True)
    ax2.spines["right"].set_linewidth(0.5)
    ax2.spines["right"].set_color("#888888")

    ax2.fill_between(
        ctx_t,
        0.0,
        cob_n,
        color=COB_COLOR,
        alpha=COB_ALPHA,
        zorder=2,
        label="COB",
    )
    ax2.plot(
        ctx_t,
        cob_n,
        color=COB_COLOR,
        lw=COB_LW,
        ls=":",
        alpha=min(COB_ALPHA + 0.2, 1.0),
        zorder=3,
        label="_nolegend_",
    )
    ax2.plot(
        ctx_t,
        iob_n,
        color=IOB_COLOR,
        lw=IOB_LW,
        ls="--",
        alpha=IOB_ALPHA,
        zorder=4,
        label="IOB",
    )

    ax2.set_ylim(0.0, SECONDARY_YLIM_TOP)
    ax2.tick_params(
        axis="y",
        labelsize=FONT_SIZE_TICK,
        direction="in",
        labelright=is_rightmost,
        right=True,
        width=0.5,
        length=2.0,
        colors="#555555",
    )
    if is_rightmost:
        ax2.set_ylabel(
            "IOB / COB (norm.)",
            fontsize=FONT_SIZE_AXIS_LABEL - 0.5,
            color="#555555",
        )
    else:
        ax2.set_yticklabels([])

    # ── Primary axis formatting ────────────────────────────────────────────
    ax.set_xlim(ctx_t[0], fc_t[-1])
    ax.set_ylim(YLIM_BG_MIN, YLIM_BG_MAX)
    ax.set_title(model_name, fontsize=FONT_SIZE_PANEL_TITLE, pad=3)
    ax.set_xlabel("Time of day (h)", fontsize=FONT_SIZE_AXIS_LABEL)

    if is_leftmost:
        ax.set_ylabel("BG (mmol/L)", fontsize=FONT_SIZE_AXIS_LABEL)
    else:
        ax.tick_params(labelleft=False)

    # Ticks every 2 h (major) and 1 h (minor); labels show clock hour
    t_start = int(ctx_t[0])
    t_end = int(np.ceil(fc_t[-1]))
    major_ticks = np.arange(t_start, t_end + 1, 2)
    ax.set_xticks(major_ticks)
    ax.set_xticklabels([str(int(t % 24)) for t in major_ticks])
    ax.set_xticks(np.arange(t_start, t_end + 1, 1), minor=True)
    ax.tick_params(axis="x", labelsize=FONT_SIZE_TICK)
    ax.tick_params(axis="y", labelsize=FONT_SIZE_TICK)

    return ax2


# ── Candidate resolver ────────────────────────────────────────────────────────


def _resolve_candidate() -> dict:
    """Return the active candidate.

    If CANDIDATES is empty, run the search, print results, and exit so the
    user can paste the entries into the CANDIDATES table.
    """
    if CANDIDATES:
        if ACTIVE_CANDIDATE >= len(CANDIDATES):
            raise IndexError(
                f"ACTIVE_CANDIDATE={ACTIVE_CANDIDATE} is out of range; "
                f"CANDIDATES has {len(CANDIDATES)} entries."
            )
        return CANDIDATES[ACTIVE_CANDIDATE]

    print(
        "CANDIDATES is empty.\n"
        "Running search — this loads three NPZ files (~18 MB total).\n"
        "Once you have the results, paste them into CANDIDATES and set "
        "ACTIVE_CANDIDATE to avoid re-running the search on every render.\n"
    )
    found = find_candidates(top_n=SEARCH_TOP_N)
    _print_candidates(found)
    if not found:
        sys.exit(1)
    return found[0]


# ── Figure builder ────────────────────────────────────────────────────────────


def build_figure(output_stem: str | None = None) -> None:
    """Build and save the three-model forecast row figure."""
    _apply_rcparams()

    stem = output_stem or OUTPUT_STEM
    model_names = list(RUN_DIRS.keys())
    n_models = len(model_names)

    candidate = _resolve_candidate()
    ep_idx = candidate["episode_idx"]
    ep_id = candidate["episode_id"]
    pid = candidate["patient_id"]
    anchor_dt = pd.Timestamp(candidate["anchor"])

    print(f"\nRendering: {ep_id}  (idx={ep_idx}, anchor={anchor_dt.date()})")
    print(
        f"  min BG = {candidate.get('min_bg', '?')} mmol/L  |  "
        f"RMSE: C2={candidate.get('rmse_c2','?')}  "
        f"Mo={candidate.get('rmse_mo','?')}  "
        f"TFT={candidate.get('rmse_tft','?')}"
    )

    print("Loading NPZ files…")
    npzs = {m: _load_npz(m) for m in model_names}

    print(f"Loading patient context data ({pid})…")
    ctx_data = load_context_data(pid, anchor_dt)

    ctx_t, fc_t = _make_time_axes()

    fig, axes = plt.subplots(
        1,
        n_models,
        figsize=(FIGURE_WIDTH_IN, FIGURE_HEIGHT_IN),
    )
    fig.subplots_adjust(
        left=SUBPLOT_LEFT,
        right=SUBPLOT_RIGHT,
        top=SUBPLOT_TOP,
        bottom=SUBPLOT_BOTTOM,
        wspace=SUBPLOT_WSPACE,
    )

    for col, (ax, model_name) in enumerate(zip(axes, model_names)):
        plot_panel(
            ax=ax,
            model_name=model_name,
            episode_idx=ep_idx,
            npz=npzs[model_name],
            ctx_data=ctx_data,
            ctx_t=ctx_t,
            fc_t=fc_t,
            is_leftmost=(col == 0),
            is_rightmost=(col == n_models - 1),
        )

    # Ensure all primary BG axes share the same y-limits
    for ax in axes:
        ax.set_ylim(YLIM_BG_MIN, YLIM_BG_MAX)

    # ── Shared figure legend ───────────────────────────────────────────────
    # Collect handles from the leftmost primary axis (canonical set)
    h_primary, l_primary = axes[0].get_legend_handles_labels()

    # IOB / COB handles (same normalised representation for every panel)
    iob_handle = mlines.Line2D(
        [],
        [],
        color=IOB_COLOR,
        lw=IOB_LW,
        ls="--",
        alpha=IOB_ALPHA,
        label="IOB",
    )
    cob_handle = mpatches.Patch(
        color=COB_COLOR,
        alpha=COB_ALPHA + 0.2,
        label="COB",
    )

    all_handles = h_primary + [iob_handle, cob_handle]
    all_labels = l_primary + ["IOB", "COB"]

    # Deduplicate preserving insertion order
    seen_labels: dict[str, object] = {}
    for h, lbl in zip(all_handles, all_labels):
        if lbl not in seen_labels and not lbl.startswith("_nolegend_"):
            seen_labels[lbl] = h

    fig.legend(
        list(seen_labels.values()),
        list(seen_labels.keys()),
        loc=LEGEND_LOC,
        bbox_to_anchor=LEGEND_BBOX,
        ncol=LEGEND_NCOL,
        fontsize=FONT_SIZE_LEGEND,
        frameon=LEGEND_FRAME,
    )

    # ── Save ──────────────────────────────────────────────────────────────
    OUTPUT_DIR.mkdir(parents=True, exist_ok=True)
    for fmt in OUTPUT_FORMATS:
        out = OUTPUT_DIR / f"{stem}.{fmt}"
        kwargs: dict = {"bbox_inches": "tight"}
        if fmt == "png":
            kwargs["dpi"] = OUTPUT_DPI
        fig.savefig(out, **kwargs)
        print(f"Saved → {out}")

    plt.close(fig)


# ── CLI ───────────────────────────────────────────────────────────────────────


def _parse_args() -> argparse.Namespace:
    p = argparse.ArgumentParser(
        description=__doc__,
        formatter_class=argparse.RawDescriptionHelpFormatter,
    )
    p.add_argument(
        "--find-candidates",
        action="store_true",
        help=(
            "Search for the best shared hypo episodes across all three models "
            "and print ready-to-paste entries for the CANDIDATES table."
        ),
    )
    p.add_argument(
        "--top-n",
        type=int,
        default=SEARCH_TOP_N,
        metavar="N",
        help=f"Number of candidates to print (default: {SEARCH_TOP_N}).",
    )
    p.add_argument(
        "--output",
        default=None,
        metavar="STEM",
        help=(
            f"Output filename stem without extension (default: {OUTPUT_STEM!r}). "
            "Files are written to results/figures/."
        ),
    )
    return p.parse_args()


def main() -> None:
    args = _parse_args()
    if args.find_candidates:
        cands = find_candidates(top_n=args.top_n)
        _print_candidates(cands)
        return
    build_figure(output_stem=args.output)


if __name__ == "__main__":
    main()
