NaiveForecaster:
  strategy:
    type: list
    values: ["last", "mean"]

AutoREG:
  lags:
    type: list
    values:
      [
        1,
        2,
        3,
        4,
        6,
        8,
        12,
        16,
        20,
        24,
        28,
        32,
        36,
        40,
        44,
        48,
        52,
        56,
        60,
        64,
        68,
        72,
      ]
  trend:
    type: list
    values: ["n", "c", "t", "ct"]
  seasonal:
    type: list
    values: [False]

AutoARIMA:
  start_p:
    type: list
    values: [2]
  max_p:
    type: list
    values: [72]
  start_q:
    type: list
    values: [2]
  max_q:
    type: list
    values: [72]
  seasonal:
    type: list
    values: [False]
  n_jobs:
    type: list
    values: [-1]

VARReduce:
  regressor:
    type: regressor
    estimators: ["LinearRegression", "Lasso", "Ridge", "ElasticNet"]
    estimator_kwargs: [{}, {}, {}, {}]
  lags:
    type: int
    range: [4, 72]
