AutoREG:
  lags:
    type: list
    values: [1, 2, 3, 4]
  trend:
    type: list
    values: ["n", "c"]
  seasonal:
    type: list
    values: [False]

AutoARIMA:
  start_p:
    type: list
    values: [2]
  max_p:
    type: list
    values: [72]
  start_q:
    type: list
    values: [2]
  max_q:
    type: list
    values: [72]
  seasonal:
    type: list
    values: [False]
  n_jobs:
    type: list
    values: [-1]

VARReduce:
  regressor:
    type: regressor
    estimators: ["LinearRegression", "Lasso", "Ridge", "ElasticNet"]
    estimator_kwargs: [{}, {}, {}, {}]
  lags:
    type: int
    range: [4, 72]
