NeuralForecastRNN:
  freq:
    type: list
    values: [1]
  futr_exog_list:
    type: list
    values: [[
      "hr-0:00",
      "steps-0:00",
      "cals-0:00",
      "cob",
      "carb_availability",
      "insulin_availability",
      "iob"
    ]]
  # NOTE: max number of batches to train
  # max_steps:
  #   type: list
  #   values: [5]

  encoder_activation:
    type: list
    values: ['relu', 'tanh']

NeuralForecastLSTM:
  freq:
    type: list
    values: [1]
  futr_exog_list:
    type: list
    values: [[
      "hr-0:00",
      "steps-0:00",
      "cals-0:00",
      "cob",
      "carb_availability",
      "insulin_availability",
      "iob"
    ]]
  encoder_n_layers:
    type: list
    values: [3]
  encoder_dropout: # for overfitting. if underfitting, set to 0
    type: list
    values: [0.2]
  decoder_layers:
    type: list
    values: [3]

PytorchForecastingTFT:
  model_params:
    type: list
    values: [
      {
        "hidden_size": 64,
        "dropout": 0.1,
        "num_heads": 4,
        "num_layers": 3,
        "lstm_layers": 2
      }
    ]
