NeuralForecastRNN:
  inference_input_size:
    type: list
    values: [72]
  encoder_n_layers:
    type: int
    range: [2, 8]
  encoder_hidden_size:
    type: list
    values: [32, 64, 128, 256, 512]
  encoder_activation:
    type: list
    values: ["relu", "tanh"]
  context_size:
    type: list
    values: [8, 16, 24, 32, 40, 48, 60, 72]
  decoder_hidden_size:
    type: list
    values: [32, 64, 128, 256, 512]
  decoder_layers:
    type: int
    range: [2, 8]
  max_steps:
    type: list
    values: [1000]
  learning_rate:
    type: list
    values: [0.1, 0.01, 0.001, 0.0001]
