AutoARIMA:
  seasonal_order:
    type: list
    values: [[0, 1, 1, 7], [1, 1, 1, 7]]
  max_order:
    type: int
    range: [1, 5]
  with_intercept:
    type: bool
    values: [true, false]

ExpSmoothing:
  trend:
    type: list
    values: [add, mul, none]
  seasonal:
    type: list
    values: [add, none]
  seasonal_periods:
    type: int
    range: [2, 12]

NaiveForecaster:
  strategy:
    type: list
    values: ["last", "mean", "drift"]
  window_length:
    type: int
    range: [1, 10]  # Window size for "mean" strategy, ignored for "last"
  sp:
    type: int
    range: [1, 12]  # Seasonal periodicity, useful for monthly/weekly data
