model_path: autogluon/chronos-2
context_length: 512
forecast_length: 96
training_mode: fine_tune
freeze_backbone: false
fine_tune_steps: 25000
fine_tune_lr: 5.0e-05
fine_tune_batch_size: 128
covariate_cols:
- iob
- insulin_availability
target_col: bg_mM
patient_col: p_num
time_col: datetime
interval_mins: 5
eval_metric: RMSE
enable_ensemble: false
